image: robertcnelson/ubuntu-2004-yocto:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.beagleboard.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  script:
    - source openembedded-core/oe-init-build-env build/light-fm
    - MACHINE=light-beagle bitbake light-fm-image-linux
