image: robertcnelson/ubuntu-2004-yocto:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.beagleboard.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  script:
    - echo 'SSTATE_MIRRORS = "file://.* http://192.168.3.192/sstate-cache/PATH"' >> ./build/light-fm/conf/local.conf
    - echo 'SOURCE_MIRROR_URL = "http://192.168.3.192/downloads/"' >> ./build/light-fm/conf/local.conf
    - source openembedded-core/oe-init-build-env build/light-fm
    - MACHINE=light-beagle bitbake light-fm-image-linux
