image: robertcnelson/ubuntu-2004-yocto:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.beagleboard.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH"
  paths:
    - thead-build/downloads/*.tar.bz2
    - thead-build/downloads/*.tar.gz
    - thead-build/downloads/*.tar.xz
    - thead-build/sstate-cache/*

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - source openembedded-core/oe-init-build-env thead-build/light-fm
    - mkdir -p ../downloads ; rsync -av /mnt/yocto-cache/beaglev-ahead/Linux_SDK_V1.1.2/downloads/ ../downloads/ || true
    - BB_NUMBER_THREADS=8 MACHINE=light-beagle bitbake -k thead-image-linux || BB_NUMBER_THREADS=2 MACHINE=light-beagle bitbake -k thead-image-linux || true
    - cp -v ./tmp-glibc/deploy/images/light-beagle/u-boot-with-spl.bin ../../deploy/ || true
    - cp -v ./tmp-glibc/deploy/images/light-beagle/boot.ext4 ../../deploy/ || true
    - cp -v ./tmp-glibc/deploy/images/light-beagle/light-fm-image-linux-light-beagle.ext4 ../../deploy/root.ext4 || true
    - xz -vT8 deploy/boot.ext4 || true
    - xz -vT8 deploy/root.ext4 || true
    - cat /builds/beaglev-ahead/xuantie-yocto/thead-build/light-fm/tmp-glibc/work/riscv64-oe-linux/vi-sensor/1.0-r0/temp/log.do_compile.* || true
  artifacts:
    expire_in: 5 days
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "deploy/fastboot_emmc.sh"
      - "deploy/u-boot-with-spl.bin"
      - "deploy/boot.ext4.xz"
      - "deploy/root.ext4.xz"

