image: robertcnelson/debian-bullseye-slim-yocto:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.beagleboard.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

cache:
  key: "$CI_PROJECT_NAME-Linux_SDK_V1.1.2-light-beagle"
  paths:
    - thead-build/sstate-cache/*

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - source openembedded-core/oe-init-build-env thead-build/light-fm
    - mkdir -p ../downloads ; rsync -a /mnt/yocto-cache/beaglev-ahead/Linux_SDK_V1.1.2/downloads/ ../downloads/ || true
    - rm -rfv ../downloads/git2/git.beagleboard.org.beaglev-ahead.beaglev* || true
    - rm -rfv ../downloads/git2_git.beagleboard.org.beaglev-ahead.beaglev* || true
    - du -sh ../downloads/
    - MACHINE=light-beagle bitbake -c cleansstate opensbi u-boot linux-thead || true
    - BB_NUMBER_THREADS=4 MACHINE=light-beagle bitbake -k thead-image-linux || true
    - cp -v ./tmp-glibc/deploy/images/light-beagle/u-boot-with-spl.bin ../../deploy/ || true
    - cp -v ./tmp-glibc/deploy/images/light-beagle/boot.ext4 ../../deploy/ || true
    - cp -v ./tmp-glibc/deploy/images/light-beagle/thead-image-linux-light-beagle-*.rootfs.ext4 ../../deploy/root.ext4 || true
    - cd /builds/beaglev-ahead/xuantie-yocto/
    - xz -vT8 deploy/boot.ext4 || true
    - xz -vT8 deploy/root.ext4 || true
  artifacts:
    expire_in: 5 days
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "deploy/fastboot_emmc.sh"
      - "deploy/u-boot-with-spl.bin"
      - "deploy/boot.ext4.xz"
      - "deploy/root.ext4.xz"

