image: robertcnelson/ubuntu-2004-yocto:latest

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.beagleboard.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  script:
    - ls -lha /mnt/yocto-cache/
    - echo 'SOURCE_MIRROR_URL = "http://192.168.3.192/downloads/"' >> ./build/light-fm/conf/local.conf
    - echo 'DL_DIR = "/mnt/yocto-cache/thead/downloads"' >> ./build/light-fm/conf/local.conf
    - echo 'SSTATE_DIR = "/mnt/yocto-cache/thead/sstate-cache"' >> ./build/light-fm/conf/local.conf
    - source openembedded-core/oe-init-build-env build/light-fm
    - MACHINE=light-beagle bitbake light-fm-image-linux --runall=fetch
#    - MACHINE=light-beagle bitbake light-fm-image-linux
#  artifacts:
#    paths:
#      - "tmp-glibc/deploy/images/light-beagle/u-boot-with-spl.bin"
#      - "tmp-glibc/deploy/images/light-beagle/boot.ext4"
#      - "tmp-glibc/deploy/images/light-beagle/light-fm-image-linux-light-beagle.ext4"
