image: robertcnelson/ubuntu-2004-yocto:latest

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - source openembedded-core/oe-init-build-env thead-build/light-fm
    - mkdir ../downloads ; rsync -av /mnt/yocto-cache/beaglev-ahead/Linux_SDK_V1.1.2/downloads/ ../downloads/
    - MACHINE=light-beagle bitbake -k thead-image-linux
